name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


# name: Build and Publish

# on:
#   push:
#     branches: [main]
 
#   pull_request: 
#     branches: [main]


# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:

#       - uses: actions/checkout@v2
#         echo: "Checking out main branch"

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build image and push to Docker Hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     tags: |
      #       nodejs-docker:latest 
      #     push: ${{ github.ref == 'refs/heads/main' }}

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
